// Generated by pgen from examples/users_pg/queries.sql against users_pg. Do not edit: change the SQL and run pgen again.
//
// Each query is a function that runs it (`<name>`: the whole reply and a status, 0 for ok) and one
// accessor per result column (`<name>_<column>`, read from a row as `pg.first_row`/`pg.next_row` give
// it; `_is_null` where the column can be NULL).
edition 5;

module queries;

import std.buffer;
import pg;

// count_users: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn count_users[&h, &c](heap: &!h Heap, conn: &!c Conn) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.extended(heap, conn, "select count(*) as total from users", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn count_users_total[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn count_users_total_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 0);
    return from < 0;
}

// list_users: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn list_users[&h, &c](heap: &!h Heap, conn: &!c Conn, limit: int, offset: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, limit);
    ps = pg.param_int(heap, ps, offset);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.extended(heap, conn, "select id, name, email, age, role, tags from users order by id limit $1 offset $2", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn list_users_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn list_users_name[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 1);
}

pub fn list_users_email[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 2);
}

pub fn list_users_email_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 2);
    return from < 0;
}

pub fn list_users_age[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 3);
    return pg.int_text(m, from, to);
}

pub fn list_users_age_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 3);
    return from < 0;
}

pub fn list_users_role[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 4);
}

pub fn list_users_role_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 4);
    return from < 0;
}

pub fn list_users_tags[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 5);
}

pub fn list_users_tags_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 5);
    return from < 0;
}

// get_user: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn get_user[&h, &c](heap: &!h Heap, conn: &!c Conn, id: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.extended(heap, conn, "select id, name, email, age, role, tags from users where id = $1", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn get_user_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn get_user_name[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 1);
}

pub fn get_user_email[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 2);
}

pub fn get_user_email_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 2);
    return from < 0;
}

pub fn get_user_age[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 3);
    return pg.int_text(m, from, to);
}

pub fn get_user_age_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 3);
    return from < 0;
}

pub fn get_user_role[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 4);
}

pub fn get_user_role_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 4);
    return from < 0;
}

pub fn get_user_tags[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 5);
}

pub fn get_user_tags_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 5);
    return from < 0;
}

// add_user: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn add_user[&h, &c, &a1, &a2, &a4, &a5](heap: &!h Heap, conn: &!c Conn, name: &a1 [byte], email: &a2 [byte], email_given: bool, age: int, age_given: bool, role: &a4 [byte], role_given: bool, tags: &a5 [byte], tags_given: bool) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param(heap, ps, name);
    if email_given {
        ps = pg.param(heap, ps, email);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if age_given {
        ps = pg.param_int(heap, ps, age);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if role_given {
        ps = pg.param(heap, ps, role);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if tags_given {
        ps = pg.param(heap, ps, tags);
    } else {
        ps = pg.param_null(heap, ps);
    }
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.extended(heap, conn, "insert into users (name, email, age, role, tags) values ($1, $2, $3, $4, $5) returning id", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn add_user_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

// delete_user: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn delete_user[&h, &c](heap: &!h Heap, conn: &!c Conn, id: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.extended(heap, conn, "delete from users where id = $1", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}
